### ISSUE TITLE
Could not resolve host: rest.nexmo.com

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/nexmo-notification-channel#79]
### Vonage Notification Channel Version

3.2.1

### Laravel Version

10.14.1

### PHP Version

8.1.20

### Database Driver & Version

MySQL

### Description

I'm getting some job failures when attempting to send SMS messages, looks like some referenes to nexmo still?

```php
GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: rest.nexmo.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://rest.nexmo.com/sms/json in /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish()
#3 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(55): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()
#9 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Client.php(333): GuzzleHttp\HandlerStack->__invoke()
#11 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Client.php(107): GuzzleHttp\Client->transfer()
#12 /var/www/snapisms-api/vendor/guzzlehttp/guzzle/src/Client.php(138): GuzzleHttp\Client->sendAsync()
#13 /var/www/snapisms-api/vendor/vonage/client-core/src/Client.php(475): GuzzleHttp\Client->sendRequest()
#14 /var/www/snapisms-api/vendor/vonage/client-core/src/Client/APIResource.php(123): Vonage\Client->send()
#15 /var/www/snapisms-api/vendor/vonage/client-core/src/SMS/Client.php(49): Vonage\Client\APIResource->create()
#16 /var/www/snapisms-api/vendor/laravel/vonage-notification-channel/src/Channels/VonageSmsChannel.php(71): Vonage\SMS\Client->send()
```

### Steps To Reproduce

Something going on at:

> vonage-notification-channel/src/Channels/VonageSmsChannel.php(71): Vonage\SMS\Client->send()

**Comment by driesvints** [comment]
This url isn't directly used in this package. Please report this to Vonage.
